Repository Step3-kakao-tech-campus/Team8_FE, pull requests merged in 2023-10, with the labels that each got.

#43 Feature/절대경로설정
  craco.config.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ProfileMenu.tsx
  src/index.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/SignUpPage.tsx
  src/test/pages/SignUpPage.test.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: ⚙️ Setting

#72 Feature/페이지 내부 공통 컨테이너
  src/App.tsx
  src/components/MainLayout.tsx
  src/components/PageContainer.tsx
  src/components/PageLayout.tsx
  src/components/PageTitleSection.tsx
  src/components/RecentChangeList.tsx
  src/index.tsx
Labels: ✨ Feature

#73 UI 보완
  src/components/GroupCard.tsx
  src/components/GroupCreateCompleteSection.tsx
  src/components/GroupCreateNameSection.tsx
  src/components/GroupCreateNickNameSection.tsx
  src/components/GroupCreatePhotoSection.tsx
  src/components/OfficialGroup.tsx
  src/components/PasswordChangeModal.tsx
  src/components/SearchInput.tsx
  src/pages/GroupCreatePage.tsx
  src/pages/GroupMyPage.tsx
  src/pages/GroupSearchResultPage.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  tailwind.config.js
Labels: ✨ Feature, 🔨 Refactor

#74 신고페이지 UI 구현
  src/index.tsx
  src/pages/ReportPage.tsx
Labels: ✨ Feature

#75 내 문서 기여 목록 페이지 UI 구현
  src/components/ContributeAccordion.tsx
  src/components/ContributeList.tsx
  src/components/Pagination.tsx
  src/dummy/group.ts
  src/pages/MyContributePage.tsx
Labels: ✨ Feature

#91 Feature/프로젝트 dependency 충돌 해결
  package-lock.json
  package.json
Labels: 🐞 BugFix

#100 Feature/회원가입 페이지 기능 구현
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/apis/authApi.ts
  src/apis/axios.ts
  src/apis/queryClient.ts
  src/constants/errorMsg.ts
  src/constants/queryKeys.ts
  src/constants/validationPatterns.ts
  src/pages/SignUpPage.tsx
  src/test/pages/LoginPage.test.tsx
  src/test/pages/SignUpPage.test.tsx
  src/test/utils/TestWrapper.tsx
  tailwind.config.js
  tsconfig.paths.json
Labels: ✨ Feature

#109 로그인 기능 구현
  src/apis/authApi.ts
  src/pages/LoginPage.tsx
  src/utils/serverError.ts
  tsconfig.paths.json
Labels: ✨ Feature

#113 Feature/카카오 로그인
  src/index.tsx
  src/pages/KakaoLoginPage.tsx
  src/pages/LoginPage.tsx
Labels: ✨ Feature
