Repository Step3-kakao-tech-campus/Team8_FE, pull requests merged in 2023-11, with the labels that each got.

#120 비밀번호 찾기 기능 구현
  src/apis/authApi.ts
  src/components/Modal/PasswordFindModal.tsx
  src/pages/LoginPage.tsx
  src/utils/serverError.ts
Labels: ✨ Feature

#119 페이지 검색 및 생성
  src/apis/pageApi.ts
  src/components/Common/SearchInput.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Modal/PageCreateModal.tsx
  src/constants/queryKeys.ts
  src/index.tsx
  src/pages/SearchResultPage.tsx
Labels: ✨ Feature

#122 Feature/로그인 후 토큰 저장
  package-lock.json
  package.json
  src/apis/authApi.ts
  src/components/Header/Header.tsx
  src/components/Header/HeaderMenu.tsx
  src/constants/recoilKeys.ts
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/recoil/atoms/auth.ts
Labels: ✨ Feature

#124 비밀번호 변경
  src/apis/authApi.ts
  src/components/Modal/PasswordChangeModal.tsx
Labels: ✨ Feature

#126 Feature/메인페이지 api 연결
  src/apis/dto.ts
  src/apis/mainApi.ts
  src/assets/images/logo/logo.svg
  src/components/Home/GroupCard.tsx
  src/components/Home/GroupList.tsx
  src/components/Home/OfficialGroup.tsx
  src/components/Page/Common/LikeDislikeButton.tsx
  src/components/Page/Common/RecentChangeList.tsx
  src/constants/queryKeys.ts
  src/pages/GroupMainPage.tsx
  src/pages/HomePage.tsx
  src/pages/SearchResultPage.tsx
Labels: ✨ Feature

#132 마이페이지 조회
  src/apis/authApi.ts
  src/apis/dto.ts
  src/constants/queryKeys.ts
  src/pages/MyPage.tsx
Labels: ✨ Feature

#135 포스트 생성 및 수정
  src/apis/postApi.ts
  src/components/Page/Post/AddPostButton.tsx
  src/components/Page/Post/Editor/Ckviewer.tsx
  src/components/Page/Post/Post.tsx
  src/pages/GroupMainPage.tsx
  src/pages/PostEditPage.tsx
Labels: ✨ Feature

#156 대표 닉네임 변경
  src/apis/authApi.ts
  src/components/MyPage/ContributeList.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature

#158 내문서기여목록 api연결
  public/data/groupMembers.json
  src/apis/dto.ts
  src/apis/groupApi.ts
  src/components/GroupCreate/GroupCreateNickNameSection.tsx
  src/components/JoinGroup/UnOfficialClosedGroup.tsx
  src/components/JoinGroup/UnOfficialOpenedGroup.tsx
  src/components/MyPage/ContributeAccordion.tsx
  src/components/MyPage/ContributeList.tsx
  src/constants/errorMsg.ts
  src/constants/queryKeys.ts
  src/index.tsx
  src/pages/GroupJoinPage.tsx
  src/pages/GroupMyPage.tsx
  src/pages/MyContributePage.tsx
  src/utils/Form/nickName.ts
  src/utils/time.ts
Labels: ✨ Feature

#168 그룹초대링크 api연결
  src/App.tsx
  src/apis/dto.ts
  src/apis/groupApi.ts
  src/apis/queryClient.ts
  src/components/Error/ErrorBoundary.tsx
  src/components/Error/ErrorFallback.tsx
  src/components/GroupCreate/GroupCreateCompleteSection.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderMenu.tsx
  src/components/Invite/InviteFetcher.tsx
  src/components/JoinGroup/UnOfficialClosedGroup.tsx
  src/components/JoinGroup/UnOfficialOpenedGroup.tsx
  src/components/Layout/MainLayout.tsx
  src/components/Layout/NoHeaderLayout.tsx
  src/components/Layout/PageLayout.tsx
  src/components/Modal/InviteModal.tsx
  src/constants/errorMsg.ts
  src/constants/queryKeys.ts
  src/hooks/useAlert.ts
  src/hooks/useJoinMutation.ts
  src/index.tsx
  src/pages/GroupJoinPage.tsx
  src/pages/InviteProcessPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/tailwind.css
  src/utils/Form/nickName.ts
Labels: ✨ Feature

#169 페이지 태그 기능
  ckeditor5/src/ckeditor.ts
  src/apis/pageApi.ts
  src/components/Modal/AddLinkModal.tsx
  src/components/Page/Post/Editor/Ckeditor.tsx
  src/components/Page/Post/Editor/Editor.css
  src/constants/queryKeys.ts
  src/pages/PostEditPage.tsx
  src/pages/SearchResultPage.tsx
Labels: ✨ Feature

#173 포스트 히스토리, 신고
  src/apis/postApi.ts
  src/components/Page/Post/Post.tsx
  src/components/PostHistoryAccordion.tsx
  src/constants/queryKeys.ts
  src/index.tsx
  src/pages/PostHistoryPage.tsx
  src/pages/ReportPage.tsx
Labels: ✨ Feature

#136 회원 탈퇴 api 연결
  src/apis/authApi.ts
  src/components/Header/HeaderMenu.tsx
  src/components/Modal/AuthDeleteModal.tsx
  src/pages/MyPage.tsx
Labels: ✨ Feature

#151 그룹탈퇴 api 연결
  src/apis/groupApi.ts
  src/components/Modal/GroupQuitModal.tsx
  src/components/Modal/QuitModal.tsx
  src/pages/GroupMyPage.tsx
Labels: ✨ Feature, 💤 API 대기중

#164 카카오 로그인 api 연결
  src/apis/authApi.ts
  src/constants/queryKeys.ts
  src/index.tsx
  src/pages/KakaoLoginPage.tsx
Labels: ✨ Feature, 💤 API 대기중

#159 댓글 api 연결
  src/apis/commentApi.ts
  src/components/Modal/ConfirmCancelModal.tsx
  src/components/Page/Post/Comment.tsx
  src/components/Page/Post/CommentList.tsx
  src/components/Page/Post/Editor/Ckviewer.tsx
  src/components/Page/Post/Post.tsx
  src/constants/queryKeys.ts
  src/pages/GroupMainPage.tsx
  src/pages/PostEditPage.tsx
Labels: ✨ Feature, 💤 API 대기중

#175 미가입그룹 접근처리
  src/components/Error/ErrorBoundary.tsx
  src/components/Error/ErrorFallback.tsx
  src/components/Error/InviteErrorFallback.tsx
  src/components/GroupCreate/GroupCreateNameSection.tsx
  src/components/JoinGroup/UnOfficialClosedGroup.tsx
  src/components/JoinGroup/UnOfficialOpenedGroup.tsx
  src/components/Layout/MainLayout.tsx
  src/components/Layout/NoHeaderLayout.tsx
  src/components/Layout/PageLayout.tsx
  src/components/Modal/GroupMemberListModal.tsx
  src/constants/errorMsg.ts
  src/pages/GroupJoinPage.tsx
  src/pages/GroupMainPage.tsx
  src/pages/InviteProcessPage.tsx
  src/pages/SearchResultPage.tsx
Labels: 🐞 BugFix

#192 Docs: 프로젝트 리드미 작성
  README.md
Labels: 📃 Docs
